version: '3.1'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgroot
      POSTGRES_DB: messager-collector-db